DROP TABLE IF EXISTS Kayttaja CASCADE;

DROP TABLE IF EXISTS Ostoslista CASCADE;

DROP TABLE IF EXISTS Ostos CASCADE;

DROP TABLE IF EXISTS Raaka_aine CASCADE;

DROP TABLE IF EXISTS Ruokalaji CASCADE;

DROP TABLE IF EXISTS Ruokalajin_aines CASCADE;


