DROP TABLE IF EXISTS Kayttaja CASCADE;

DROP TABLE IF EXISTS Ostoslista CASCADE;

DROP TABLE IF EXISTS Raaka_aine CASCADE;

DROP TABLE IF EXISTS Ateriakokonaisuus CASCADE;

DROP TABLE IF EXISTS Ruokalaji CASCADE;

DROP TABLE IF EXISTS Kuva CASCADE;

DROP TABLE IF EXISTS Ateria CASCADE;

DROP TABLE IF EXISTS Ruokalajin_aines CASCADE;


